### ISSUE TITLE
关于你那个Warp的教程的IPv6问题

### ISSUE THREAD

**Issue by toyo2333** [hausa-han/spiders#3]
我都跑通了流程，但出现一个问题：

前提：

双栈VPS机器，设置了代理，安装了Warp，我使用的是代理模式，然后将ChatGPT,ipw.cn等的访问用Xray路由转发到Warp sock5 代理出站

情况：

1，当我不用Warp时候，本地电脑上浏览器都是可以使用IPv6打开ChatGTP和ipw.cn的,都是优先使用IPv6。

---可以直接打开https://chat.openai.com/cdn-cgi 和 https://ipw.cn/ 查看结果

2，开启并连接Warp之后，的ipv4和ipv6地址都成功获取了Warp的地址。但是访问ChatGTP和ipw.cn却变成了用IPv4优先了。

3，我以为是vps的问题，我在VPS直接使用warp代理访问ChatGTP或者ipw.cn的测试API，却都都能使用IPv6，

例1： curl https://chat.openai.com/cdn-cgi/trace --proxy socks5://127.0.0.1:40000，结果显示warp=on, ip是一个Warp节点的IPV6的地址 IPv6优先访问

例2：curl test.ipw.cn --proxy socks5://127.0.0.1:40000 APi返回给我的也是IPv6的Warp地址

说明VPS上使用Warp socks5代理模式访问目标站点，IPv6优先OK的

我的问题来了：为什么在我本地电脑上就不行了呢？ 上面的123已经说明了，VPS的xray路由里把域名加进去转发到Warp sock5 Proxy之后，就显示IPv4访问了。去掉，就能IPv6，其他条件都没变。

这是什么原因呢？应该不是我的电脑或者浏览器或者VPS的问题把，是我的warp proxy哪里设置错误了么？盼望大佬来解答一下。

PS，不是说IPv4就不行，都能用，我就是想知道为啥？

**Comment by hausa-han** [comment]
您好，抱歉这个问题超出了我的知识范围，可以去到我fork的那个仓库的大佬那里问一下，他可能更懂一点。或者访问https://developers.cloudflare.com/support/network/understanding-and-configuring-cloudflares-ipv6-support/根据最后一个小标题中的内容提交issue。
我这里没法进行测试因为我的vps是搬瓦工最便宜的套餐，只有v4。。。

**Comment by hausa-han** [comment]
您好，抱歉这个问题超出了我的知识范围，可以去到我fork的那个仓库的大佬那里问一下，他可能更懂一点。或者访问[https://developers.cloudflare.com/support/network/understanding-and-configuring-cloudflares-ipv6-support/
根据最后一个小标题中的内容提交issue。
我这里没法进行测试因为我的vps是搬瓦工最便宜的套餐，只有v4。。。

**Comment by hausa-han** [comment]
居然有v6
蛮怪的，更说明我对这个问题的不懂了hhhh

**Comment by toyo2333** [comment]
解决了，换wgcf。只接管IPv6
